name: Backend CI/CD

on:
  push:
    paths:
      - master
#      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Test Backend
        run: |
          cd backend
          mvn test

      # (Optional) Dockerize
      - name: Docker Build
        run: |
          docker build -t my-backend:latest ./backend

      - name: Docker Push
        if: success()
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-backend:latest <registry>/my-backend:latest
          docker push <registry>/my-backend:latest
